# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from ghost_schema.ghost import ghost_pb2 as ghost_dot_ghost__pb2

GRPC_GENERATED_VERSION = '1.72.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ghost/ghost_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GhostStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMatchInfo = channel.unary_unary(
                '/ghost.Ghost/GetMatchInfo',
                request_serializer=ghost_dot_ghost__pb2.MatchInfoRequest.SerializeToString,
                response_deserializer=ghost_dot_ghost__pb2.MatchInfoResponse.FromString,
                _registered_method=True)
        self.GetMatchStatus = channel.unary_unary(
                '/ghost.Ghost/GetMatchStatus',
                request_serializer=ghost_dot_ghost__pb2.MatchStatusRequest.SerializeToString,
                response_deserializer=ghost_dot_ghost__pb2.MatchStatusResponse.FromString,
                _registered_method=True)


class GhostServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMatchInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMatchStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GhostServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMatchInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMatchInfo,
                    request_deserializer=ghost_dot_ghost__pb2.MatchInfoRequest.FromString,
                    response_serializer=ghost_dot_ghost__pb2.MatchInfoResponse.SerializeToString,
            ),
            'GetMatchStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMatchStatus,
                    request_deserializer=ghost_dot_ghost__pb2.MatchStatusRequest.FromString,
                    response_serializer=ghost_dot_ghost__pb2.MatchStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ghost.Ghost', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ghost.Ghost', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Ghost(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMatchInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ghost.Ghost/GetMatchInfo',
            ghost_dot_ghost__pb2.MatchInfoRequest.SerializeToString,
            ghost_dot_ghost__pb2.MatchInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMatchStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ghost.Ghost/GetMatchStatus',
            ghost_dot_ghost__pb2.MatchStatusRequest.SerializeToString,
            ghost_dot_ghost__pb2.MatchStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
