# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ghost/ghost.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'ghost/ghost.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11ghost/ghost.proto\x12\x05ghost\"%\n\x10MatchInfoRequest\x12\x11\n\tmatch_urn\x18\x01 \x01(\t\"}\n\x11MatchInfoResponse\x12*\n\x03\x63s2\x18\x01 \x01(\x0b\x32\x1b.ghost.CS2MatchInfoResponseH\x00\x12.\n\x05\x64ota2\x18\x02 \x01(\x0b\x32\x1d.ghost.Dota2MatchInfoResponseH\x00\x42\x0c\n\nmatch_info\"V\n\x14\x43S2MatchInfoResponse\x12\x10\n\x08map_name\x18\x02 \x01(\t\x12\x16\n\x0emap_asset_name\x18\x03 \x01(\t\x12\x14\n\x0cgame_version\x18\x04 \x01(\t\".\n\x16\x44ota2MatchInfoResponse\x12\x14\n\x0cgame_version\x18\x02 \x01(\t\"\'\n\x12MatchStatusRequest\x12\x11\n\tmatch_urn\x18\x01 \x01(\t\"?\n\x13MatchStatusResponse\x12(\n\x0cmatch_status\x18\x01 \x01(\x0e\x32\x12.ghost.MatchStatus*a\n\x0bMatchStatus\x12\x18\n\x14MATCH_STATUS_UNKNOWN\x10\x00\x12\x1a\n\x16MATCH_STATUS_AVAILABLE\x10\x01\x12\x1c\n\x18MATCH_STATUS_UNAVAILABLE\x10\x02\x32\x93\x01\n\x05Ghost\x12\x41\n\x0cGetMatchInfo\x12\x17.ghost.MatchInfoRequest\x1a\x18.ghost.MatchInfoResponse\x12G\n\x0eGetMatchStatus\x12\x19.ghost.MatchStatusRequest\x1a\x1a.ghost.MatchStatusResponseB!\n\x0f\x63om.oddin.ghostZ\x0eoddin.gg/ghostb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ghost.ghost_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\017com.oddin.ghostZ\016oddin.gg/ghost'
  _globals['_MATCHSTATUS']._serialized_start=436
  _globals['_MATCHSTATUS']._serialized_end=533
  _globals['_MATCHINFOREQUEST']._serialized_start=28
  _globals['_MATCHINFOREQUEST']._serialized_end=65
  _globals['_MATCHINFORESPONSE']._serialized_start=67
  _globals['_MATCHINFORESPONSE']._serialized_end=192
  _globals['_CS2MATCHINFORESPONSE']._serialized_start=194
  _globals['_CS2MATCHINFORESPONSE']._serialized_end=280
  _globals['_DOTA2MATCHINFORESPONSE']._serialized_start=282
  _globals['_DOTA2MATCHINFORESPONSE']._serialized_end=328
  _globals['_MATCHSTATUSREQUEST']._serialized_start=330
  _globals['_MATCHSTATUSREQUEST']._serialized_end=369
  _globals['_MATCHSTATUSRESPONSE']._serialized_start=371
  _globals['_MATCHSTATUSRESPONSE']._serialized_end=434
  _globals['_GHOST']._serialized_start=536
  _globals['_GHOST']._serialized_end=683
# @@protoc_insertion_point(module_scope)
