syntax = "proto3";

package ghost;

option go_package = "oddin.gg/ghost";
option java_package = "com.oddin.ghost";

message MatchInfoRequest {
  string match_urn = 1;
}

message MatchInfoResponse {
  oneof match_info {
    CS2MatchInfoResponse cs2 = 1;
    Dota2MatchInfoResponse dota2 = 2;
  }

  string host = 3;
}

message CS2MatchInfoResponse {
  string map_name = 2;
  string map_asset_name = 3;
  string game_version = 4;
  // Specifies the URL for the asset of the match.
  string asset_url = 5;
}

message Dota2MatchInfoResponse {
  string game_version = 2;
  // Specifies the URL for the asset of the match.
  string asset_url = 3;
}

message MatchStatusRequest {
  string match_urn = 1;
}

enum MatchStatus {
  MATCH_STATUS_UNKNOWN = 0;
  MATCH_STATUS_AVAILABLE = 1;
  MATCH_STATUS_UNAVAILABLE = 2;
}

message MatchStatusResponse {
  MatchStatus match_status = 1;
}

message FeedbackRequest {
  FeedbackType feedback_type = 1;
  string description = 2;
  optional string email = 3;
  repeated FeedbackAttachment attachments = 4;
}

enum FeedbackType {
  FEEDBACK_TYPE_UNKNOWN = 0;
  FEEDBACK_TYPE_BUG = 1;
  FEEDBACK_TYPE_SUGGESTION = 2;
}

message FeedbackAttachment {
  string content_type = 2;  // e.g., "application/pdf"
  bytes data = 3;           // raw file bytes
}

message FeedbackResponse {}

service Ghost {
  rpc GetMatchInfo(MatchInfoRequest) returns (MatchInfoResponse);
  rpc GetMatchStatus(MatchStatusRequest) returns (MatchStatusResponse);
  rpc SendFeedback(FeedbackRequest) returns (FeedbackResponse);
}
