// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v4.25.6
// source: minigames/minigames.proto

package minigames

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StartSessionRequest starts (or restarts) a minigames session for a player.
// The client is identified by the token passed in gRPC metadata (same as the
// Ghost service), so the request body carries only the player's betting handle.
type StartSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Player identity as known to the client (e.g. their betting handle). It is
	// scoped to the authenticated client; the backend maps it to an opaque
	// player_uuid.
	BettingHandle string `protobuf:"bytes,1,opt,name=betting_handle,json=bettingHandle,proto3" json:"betting_handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSessionRequest) Reset() {
	*x = StartSessionRequest{}
	mi := &file_minigames_minigames_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionRequest) ProtoMessage() {}

func (x *StartSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minigames_minigames_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionRequest.ProtoReflect.Descriptor instead.
func (*StartSessionRequest) Descriptor() ([]byte, []int) {
	return file_minigames_minigames_proto_rawDescGZIP(), []int{0}
}

func (x *StartSessionRequest) GetBettingHandle() string {
	if x != nil {
		return x.BettingHandle
	}
	return ""
}

// Game is one entry in the minigames offering.
type Game struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human-readable game name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Full CDN asset URL for the game, with the started session's uuid appended
	// as the `session` query parameter.
	AssetUrl      string `protobuf:"bytes,2,opt,name=asset_url,json=assetUrl,proto3" json:"asset_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Game) Reset() {
	*x = Game{}
	mi := &file_minigames_minigames_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game) ProtoMessage() {}

func (x *Game) ProtoReflect() protoreflect.Message {
	mi := &file_minigames_minigames_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game.ProtoReflect.Descriptor instead.
func (*Game) Descriptor() ([]byte, []int) {
	return file_minigames_minigames_proto_rawDescGZIP(), []int{1}
}

func (x *Game) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Game) GetAssetUrl() string {
	if x != nil {
		return x.AssetUrl
	}
	return ""
}

type StartSessionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque, stable identifier for the player across sessions and games.
	PlayerUuid string `protobuf:"bytes,1,opt,name=player_uuid,json=playerUuid,proto3" json:"player_uuid,omitempty"`
	// Identifier of the session started by this call.
	SessionUuid string `protobuf:"bytes,2,opt,name=session_uuid,json=sessionUuid,proto3" json:"session_uuid,omitempty"`
	// Games available to play in this session.
	Games         []*Game `protobuf:"bytes,3,rep,name=games,proto3" json:"games,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSessionResponse) Reset() {
	*x = StartSessionResponse{}
	mi := &file_minigames_minigames_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionResponse) ProtoMessage() {}

func (x *StartSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minigames_minigames_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionResponse.ProtoReflect.Descriptor instead.
func (*StartSessionResponse) Descriptor() ([]byte, []int) {
	return file_minigames_minigames_proto_rawDescGZIP(), []int{2}
}

func (x *StartSessionResponse) GetPlayerUuid() string {
	if x != nil {
		return x.PlayerUuid
	}
	return ""
}

func (x *StartSessionResponse) GetSessionUuid() string {
	if x != nil {
		return x.SessionUuid
	}
	return ""
}

func (x *StartSessionResponse) GetGames() []*Game {
	if x != nil {
		return x.Games
	}
	return nil
}

var File_minigames_minigames_proto protoreflect.FileDescriptor

var file_minigames_minigames_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6d, 0x69, 0x6e, 0x69, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x2f, 0x6d, 0x69, 0x6e, 0x69,
	0x67, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6d, 0x69, 0x6e,
	0x69, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x22, 0x3c, 0x0a, 0x13, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a,
	0x0e, 0x62, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x62, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x48, 0x61,
	0x6e, 0x64, 0x6c, 0x65, 0x22, 0x37, 0x0a, 0x04, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x73, 0x73, 0x65, 0x74, 0x55, 0x72, 0x6c, 0x22, 0x81, 0x01,
	0x0a, 0x14, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x55, 0x75, 0x69, 0x64, 0x12, 0x25, 0x0a, 0x05, 0x67, 0x61,
	0x6d, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x69, 0x6e, 0x69,
	0x67, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x05, 0x67, 0x61, 0x6d, 0x65,
	0x73, 0x32, 0x5c, 0x0a, 0x09, 0x4d, 0x69, 0x6e, 0x69, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x4f,
	0x0a, 0x0c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1e,
	0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f,
	0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x29, 0x0a, 0x13, 0x63, 0x6f, 0x6d, 0x2e, 0x6f, 0x64, 0x64, 0x69, 0x6e, 0x2e, 0x6d, 0x69, 0x6e,
	0x69, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x5a, 0x12, 0x6f, 0x64, 0x64, 0x69, 0x6e, 0x2e, 0x67, 0x67,
	0x2f, 0x6d, 0x69, 0x6e, 0x69, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_minigames_minigames_proto_rawDescOnce sync.Once
	file_minigames_minigames_proto_rawDescData = file_minigames_minigames_proto_rawDesc
)

func file_minigames_minigames_proto_rawDescGZIP() []byte {
	file_minigames_minigames_proto_rawDescOnce.Do(func() {
		file_minigames_minigames_proto_rawDescData = protoimpl.X.CompressGZIP(file_minigames_minigames_proto_rawDescData)
	})
	return file_minigames_minigames_proto_rawDescData
}

var file_minigames_minigames_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_minigames_minigames_proto_goTypes = []any{
	(*StartSessionRequest)(nil),  // 0: minigames.StartSessionRequest
	(*Game)(nil),                 // 1: minigames.Game
	(*StartSessionResponse)(nil), // 2: minigames.StartSessionResponse
}
var file_minigames_minigames_proto_depIdxs = []int32{
	1, // 0: minigames.StartSessionResponse.games:type_name -> minigames.Game
	0, // 1: minigames.Minigames.StartSession:input_type -> minigames.StartSessionRequest
	2, // 2: minigames.Minigames.StartSession:output_type -> minigames.StartSessionResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_minigames_minigames_proto_init() }
func file_minigames_minigames_proto_init() {
	if File_minigames_minigames_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_minigames_minigames_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_minigames_minigames_proto_goTypes,
		DependencyIndexes: file_minigames_minigames_proto_depIdxs,
		MessageInfos:      file_minigames_minigames_proto_msgTypes,
	}.Build()
	File_minigames_minigames_proto = out.File
	file_minigames_minigames_proto_rawDesc = nil
	file_minigames_minigames_proto_goTypes = nil
	file_minigames_minigames_proto_depIdxs = nil
}
