// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v3.21.12
// source: minigames/minigames.proto

package minigames

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LeaderboardAggregation selects how a player's play scores are combined into
// their ranking score.
type LeaderboardAggregation int32

const (
	// Defaults to SUM.
	LeaderboardAggregation_LEADERBOARD_AGGREGATION_UNSPECIFIED LeaderboardAggregation = 0
	// Sum of the player's play scores.
	LeaderboardAggregation_LEADERBOARD_AGGREGATION_SUM LeaderboardAggregation = 1
	// The player's single highest play score.
	LeaderboardAggregation_LEADERBOARD_AGGREGATION_MAX LeaderboardAggregation = 2
)

// Enum value maps for LeaderboardAggregation.
var (
	LeaderboardAggregation_name = map[int32]string{
		0: "LEADERBOARD_AGGREGATION_UNSPECIFIED",
		1: "LEADERBOARD_AGGREGATION_SUM",
		2: "LEADERBOARD_AGGREGATION_MAX",
	}
	LeaderboardAggregation_value = map[string]int32{
		"LEADERBOARD_AGGREGATION_UNSPECIFIED": 0,
		"LEADERBOARD_AGGREGATION_SUM":         1,
		"LEADERBOARD_AGGREGATION_MAX":         2,
	}
)

func (x LeaderboardAggregation) Enum() *LeaderboardAggregation {
	p := new(LeaderboardAggregation)
	*p = x
	return p
}

func (x LeaderboardAggregation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LeaderboardAggregation) Descriptor() protoreflect.EnumDescriptor {
	return file_minigames_minigames_proto_enumTypes[0].Descriptor()
}

func (LeaderboardAggregation) Type() protoreflect.EnumType {
	return &file_minigames_minigames_proto_enumTypes[0]
}

func (x LeaderboardAggregation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LeaderboardAggregation.Descriptor instead.
func (LeaderboardAggregation) EnumDescriptor() ([]byte, []int) {
	return file_minigames_minigames_proto_rawDescGZIP(), []int{0}
}

// StartSessionRequest starts a minigames session for a player. The client is
// identified by the token passed in gRPC metadata (same as the Ghost service),
// so the request body carries only the player's betting handle.
type StartSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Player identity as known to the client (e.g. their betting handle). It is
	// scoped to the authenticated client; the backend maps it to an opaque
	// player_uuid.
	BettingHandle string `protobuf:"bytes,1,opt,name=betting_handle,json=bettingHandle,proto3" json:"betting_handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSessionRequest) Reset() {
	*x = StartSessionRequest{}
	mi := &file_minigames_minigames_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionRequest) ProtoMessage() {}

func (x *StartSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minigames_minigames_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionRequest.ProtoReflect.Descriptor instead.
func (*StartSessionRequest) Descriptor() ([]byte, []int) {
	return file_minigames_minigames_proto_rawDescGZIP(), []int{0}
}

func (x *StartSessionRequest) GetBettingHandle() string {
	if x != nil {
		return x.BettingHandle
	}
	return ""
}

// Game is one entry in the minigames offering.
type Game struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human-readable game name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Full CDN asset URL for the game, with the session token appended as the
	// `session` URL fragment (`#session=<token>`) so it stays client-side.
	AssetUrl      string `protobuf:"bytes,2,opt,name=asset_url,json=assetUrl,proto3" json:"asset_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Game) Reset() {
	*x = Game{}
	mi := &file_minigames_minigames_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game) ProtoMessage() {}

func (x *Game) ProtoReflect() protoreflect.Message {
	mi := &file_minigames_minigames_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game.ProtoReflect.Descriptor instead.
func (*Game) Descriptor() ([]byte, []int) {
	return file_minigames_minigames_proto_rawDescGZIP(), []int{1}
}

func (x *Game) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Game) GetAssetUrl() string {
	if x != nil {
		return x.AssetUrl
	}
	return ""
}

type StartSessionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque, stable identifier for the player across sessions and games.
	PlayerUuid string `protobuf:"bytes,1,opt,name=player_uuid,json=playerUuid,proto3" json:"player_uuid,omitempty"`
	// Signed, stateless session token for this session (a JWT). It is embedded in
	// each game's asset_url fragment and sent back on StartPlay/StopSession; the
	// backend keeps no session state, validating the token by signature and
	// expiry.
	SessionToken string `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	// Games available to play in this session.
	Games         []*Game `protobuf:"bytes,3,rep,name=games,proto3" json:"games,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSessionResponse) Reset() {
	*x = StartSessionResponse{}
	mi := &file_minigames_minigames_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionResponse) ProtoMessage() {}

func (x *StartSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minigames_minigames_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionResponse.ProtoReflect.Descriptor instead.
func (*StartSessionResponse) Descriptor() ([]byte, []int) {
	return file_minigames_minigames_proto_rawDescGZIP(), []int{2}
}

func (x *StartSessionResponse) GetPlayerUuid() string {
	if x != nil {
		return x.PlayerUuid
	}
	return ""
}

func (x *StartSessionResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *StartSessionResponse) GetGames() []*Game {
	if x != nil {
		return x.Games
	}
	return nil
}

// StopSessionRequest ends a player's session. The client is identified by the
// token in gRPC metadata; the player is identified by the same betting_handle
// used to start the session, so the backend need not persist the session token.
type StopSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Player identity as known to the client (the same betting_handle passed to
	// StartSession), scoped to the authenticated client.
	BettingHandle string `protobuf:"bytes,1,opt,name=betting_handle,json=bettingHandle,proto3" json:"betting_handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopSessionRequest) Reset() {
	*x = StopSessionRequest{}
	mi := &file_minigames_minigames_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSessionRequest) ProtoMessage() {}

func (x *StopSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minigames_minigames_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSessionRequest.ProtoReflect.Descriptor instead.
func (*StopSessionRequest) Descriptor() ([]byte, []int) {
	return file_minigames_minigames_proto_rawDescGZIP(), []int{3}
}

func (x *StopSessionRequest) GetBettingHandle() string {
	if x != nil {
		return x.BettingHandle
	}
	return ""
}

type StopSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopSessionResponse) Reset() {
	*x = StopSessionResponse{}
	mi := &file_minigames_minigames_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSessionResponse) ProtoMessage() {}

func (x *StopSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minigames_minigames_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSessionResponse.ProtoReflect.Descriptor instead.
func (*StopSessionResponse) Descriptor() ([]byte, []int) {
	return file_minigames_minigames_proto_rawDescGZIP(), []int{4}
}

// LeaderboardRequest asks for the top players of the authenticated client,
// ranked by their score over a time range.
type LeaderboardRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Restrict to a single game by its slug; empty means across all games.
	GameSlug string `protobuf:"bytes,1,opt,name=game_slug,json=gameSlug,proto3" json:"game_slug,omitempty"`
	// Start of the time range, inclusive. Required.
	FromTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=from_time,json=fromTime,proto3" json:"from_time,omitempty"`
	// End of the time range, inclusive. Optional; defaults to now when unset.
	ToTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=to_time,json=toTime,proto3" json:"to_time,omitempty"`
	// Maximum number of players to return. Capped at 100.
	Limit int32 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	// How to combine a player's play scores into their ranking score. Defaults
	// to SUM when unspecified.
	Aggregation   LeaderboardAggregation `protobuf:"varint,5,opt,name=aggregation,proto3,enum=minigames.LeaderboardAggregation" json:"aggregation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardRequest) Reset() {
	*x = LeaderboardRequest{}
	mi := &file_minigames_minigames_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardRequest) ProtoMessage() {}

func (x *LeaderboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minigames_minigames_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardRequest.ProtoReflect.Descriptor instead.
func (*LeaderboardRequest) Descriptor() ([]byte, []int) {
	return file_minigames_minigames_proto_rawDescGZIP(), []int{5}
}

func (x *LeaderboardRequest) GetGameSlug() string {
	if x != nil {
		return x.GameSlug
	}
	return ""
}

func (x *LeaderboardRequest) GetFromTime() *timestamppb.Timestamp {
	if x != nil {
		return x.FromTime
	}
	return nil
}

func (x *LeaderboardRequest) GetToTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ToTime
	}
	return nil
}

func (x *LeaderboardRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *LeaderboardRequest) GetAggregation() LeaderboardAggregation {
	if x != nil {
		return x.Aggregation
	}
	return LeaderboardAggregation_LEADERBOARD_AGGREGATION_UNSPECIFIED
}

// LeaderboardEntry is one player's ranking row.
type LeaderboardEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque, stable player identifier.
	PlayerUuid string `protobuf:"bytes,1,opt,name=player_uuid,json=playerUuid,proto3" json:"player_uuid,omitempty"`
	// The player's betting handle as supplied by the client.
	BettingHandle string `protobuf:"bytes,2,opt,name=betting_handle,json=bettingHandle,proto3" json:"betting_handle,omitempty"`
	// Sum of the player's play scores over the requested range and game(s).
	TotalScore    float64 `protobuf:"fixed64,3,opt,name=total_score,json=totalScore,proto3" json:"total_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardEntry) Reset() {
	*x = LeaderboardEntry{}
	mi := &file_minigames_minigames_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardEntry) ProtoMessage() {}

func (x *LeaderboardEntry) ProtoReflect() protoreflect.Message {
	mi := &file_minigames_minigames_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardEntry.ProtoReflect.Descriptor instead.
func (*LeaderboardEntry) Descriptor() ([]byte, []int) {
	return file_minigames_minigames_proto_rawDescGZIP(), []int{6}
}

func (x *LeaderboardEntry) GetPlayerUuid() string {
	if x != nil {
		return x.PlayerUuid
	}
	return ""
}

func (x *LeaderboardEntry) GetBettingHandle() string {
	if x != nil {
		return x.BettingHandle
	}
	return ""
}

func (x *LeaderboardEntry) GetTotalScore() float64 {
	if x != nil {
		return x.TotalScore
	}
	return 0
}

type LeaderboardResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Players ordered by total_score descending.
	Entries       []*LeaderboardEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardResponse) Reset() {
	*x = LeaderboardResponse{}
	mi := &file_minigames_minigames_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardResponse) ProtoMessage() {}

func (x *LeaderboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minigames_minigames_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardResponse.ProtoReflect.Descriptor instead.
func (*LeaderboardResponse) Descriptor() ([]byte, []int) {
	return file_minigames_minigames_proto_rawDescGZIP(), []int{7}
}

func (x *LeaderboardResponse) GetEntries() []*LeaderboardEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// PlayerScoreRequest asks for one player's aggregated score over a time range.
// The client is identified by the token in gRPC metadata; the player by the
// same betting_handle used elsewhere.
type PlayerScoreRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Player identity as known to the client (the same betting_handle used at
	// StartSession), scoped to the authenticated client.
	BettingHandle string `protobuf:"bytes,1,opt,name=betting_handle,json=bettingHandle,proto3" json:"betting_handle,omitempty"`
	// Start of the time range, inclusive. Required.
	FromTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=from_time,json=fromTime,proto3" json:"from_time,omitempty"`
	// End of the time range, inclusive. Optional; defaults to now when unset.
	ToTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=to_time,json=toTime,proto3" json:"to_time,omitempty"`
	// How to combine the player's play scores. Defaults to SUM when unspecified.
	Aggregation   LeaderboardAggregation `protobuf:"varint,4,opt,name=aggregation,proto3,enum=minigames.LeaderboardAggregation" json:"aggregation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerScoreRequest) Reset() {
	*x = PlayerScoreRequest{}
	mi := &file_minigames_minigames_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerScoreRequest) ProtoMessage() {}

func (x *PlayerScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minigames_minigames_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerScoreRequest.ProtoReflect.Descriptor instead.
func (*PlayerScoreRequest) Descriptor() ([]byte, []int) {
	return file_minigames_minigames_proto_rawDescGZIP(), []int{8}
}

func (x *PlayerScoreRequest) GetBettingHandle() string {
	if x != nil {
		return x.BettingHandle
	}
	return ""
}

func (x *PlayerScoreRequest) GetFromTime() *timestamppb.Timestamp {
	if x != nil {
		return x.FromTime
	}
	return nil
}

func (x *PlayerScoreRequest) GetToTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ToTime
	}
	return nil
}

func (x *PlayerScoreRequest) GetAggregation() LeaderboardAggregation {
	if x != nil {
		return x.Aggregation
	}
	return LeaderboardAggregation_LEADERBOARD_AGGREGATION_UNSPECIFIED
}

type PlayerScoreResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The player's aggregated (sum or max) play score over the range, across all
	// games. Zero when found is false.
	TotalScore float64 `protobuf:"fixed64,1,opt,name=total_score,json=totalScore,proto3" json:"total_score,omitempty"`
	// Whether the player had any scored plays in the range. Distinguishes "no
	// scored plays" from a genuine score of zero.
	Found         bool `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerScoreResponse) Reset() {
	*x = PlayerScoreResponse{}
	mi := &file_minigames_minigames_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerScoreResponse) ProtoMessage() {}

func (x *PlayerScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minigames_minigames_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerScoreResponse.ProtoReflect.Descriptor instead.
func (*PlayerScoreResponse) Descriptor() ([]byte, []int) {
	return file_minigames_minigames_proto_rawDescGZIP(), []int{9}
}

func (x *PlayerScoreResponse) GetTotalScore() float64 {
	if x != nil {
		return x.TotalScore
	}
	return 0
}

func (x *PlayerScoreResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

var File_minigames_minigames_proto protoreflect.FileDescriptor

var file_minigames_minigames_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6d, 0x69, 0x6e, 0x69, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x2f, 0x6d, 0x69, 0x6e, 0x69,
	0x67, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6d, 0x69, 0x6e,
	0x69, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3c, 0x0a, 0x13, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25,
	0x0a, 0x0e, 0x62, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x62, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x48,
	0x61, 0x6e, 0x64, 0x6c, 0x65, 0x22, 0x37, 0x0a, 0x04, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x73, 0x73, 0x65, 0x74, 0x55, 0x72, 0x6c, 0x22, 0x83,
	0x01, 0x0a, 0x14, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x25, 0x0a,
	0x05, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d,
	0x69, 0x6e, 0x69, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x05, 0x67,
	0x61, 0x6d, 0x65, 0x73, 0x22, 0x3b, 0x0a, 0x12, 0x53, 0x74, 0x6f, 0x70, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x62, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x62, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x48, 0x61, 0x6e, 0x64, 0x6c,
	0x65, 0x22, 0x15, 0x0a, 0x13, 0x53, 0x74, 0x6f, 0x70, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xfa, 0x01, 0x0a, 0x12, 0x4c, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x6c, 0x75, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x53, 0x6c, 0x75, 0x67, 0x12, 0x37, 0x0a, 0x09,
	0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x66, 0x72, 0x6f,
	0x6d, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x33, 0x0a, 0x07, 0x74, 0x6f, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x06, 0x74, 0x6f, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x12, 0x43, 0x0a, 0x0b, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x67, 0x61, 0x6d, 0x65,
	0x73, 0x2e, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x41, 0x67, 0x67,
	0x72, 0x65, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x7b, 0x0a, 0x10, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x62,
	0x6f, 0x61, 0x72, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x62, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x62, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x48, 0x61, 0x6e, 0x64, 0x6c,
	0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x63, 0x6f,
	0x72, 0x65, 0x22, 0x4c, 0x0a, 0x13, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x61, 0x72,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x07, 0x65, 0x6e, 0x74,
	0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x69, 0x6e,
	0x69, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x61,
	0x72, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73,
	0x22, 0xee, 0x01, 0x0a, 0x12, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x63, 0x6f, 0x72, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x62, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x62, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x12, 0x37,
	0x0a, 0x09, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x66,
	0x72, 0x6f, 0x6d, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x33, 0x0a, 0x07, 0x74, 0x6f, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x06, 0x74, 0x6f, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x43, 0x0a, 0x0b,
	0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x21, 0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x4c, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x4c, 0x0a, 0x13, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x63, 0x6f, 0x72, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f, 0x75,
	0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x2a,
	0x83, 0x01, 0x0a, 0x16, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x41,
	0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x0a, 0x23, 0x4c, 0x45,
	0x41, 0x44, 0x45, 0x52, 0x42, 0x4f, 0x41, 0x52, 0x44, 0x5f, 0x41, 0x47, 0x47, 0x52, 0x45, 0x47,
	0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x1f, 0x0a, 0x1b, 0x4c, 0x45, 0x41, 0x44, 0x45, 0x52, 0x42, 0x4f, 0x41,
	0x52, 0x44, 0x5f, 0x41, 0x47, 0x47, 0x52, 0x45, 0x47, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x53,
	0x55, 0x4d, 0x10, 0x01, 0x12, 0x1f, 0x0a, 0x1b, 0x4c, 0x45, 0x41, 0x44, 0x45, 0x52, 0x42, 0x4f,
	0x41, 0x52, 0x44, 0x5f, 0x41, 0x47, 0x47, 0x52, 0x45, 0x47, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f,
	0x4d, 0x41, 0x58, 0x10, 0x02, 0x32, 0xc6, 0x02, 0x0a, 0x09, 0x4d, 0x69, 0x6e, 0x69, 0x67, 0x61,
	0x6d, 0x65, 0x73, 0x12, 0x4f, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x2e,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x2e,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c, 0x0a, 0x0b, 0x53, 0x74, 0x6f, 0x70, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x2e,
	0x53, 0x74, 0x6f, 0x70, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x53,
	0x74, 0x6f, 0x70, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x4c, 0x0a, 0x0b, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x61, 0x72,
	0x64, 0x12, 0x1d, 0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x4c, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1e, 0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x4c, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x4c, 0x0a, 0x0b, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12,
	0x1d, 0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e,
	0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x29,
	0x0a, 0x13, 0x63, 0x6f, 0x6d, 0x2e, 0x6f, 0x64, 0x64, 0x69, 0x6e, 0x2e, 0x6d, 0x69, 0x6e, 0x69,
	0x67, 0x61, 0x6d, 0x65, 0x73, 0x5a, 0x12, 0x6f, 0x64, 0x64, 0x69, 0x6e, 0x2e, 0x67, 0x67, 0x2f,
	0x6d, 0x69, 0x6e, 0x69, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_minigames_minigames_proto_rawDescOnce sync.Once
	file_minigames_minigames_proto_rawDescData = file_minigames_minigames_proto_rawDesc
)

func file_minigames_minigames_proto_rawDescGZIP() []byte {
	file_minigames_minigames_proto_rawDescOnce.Do(func() {
		file_minigames_minigames_proto_rawDescData = protoimpl.X.CompressGZIP(file_minigames_minigames_proto_rawDescData)
	})
	return file_minigames_minigames_proto_rawDescData
}

var file_minigames_minigames_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_minigames_minigames_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_minigames_minigames_proto_goTypes = []any{
	(LeaderboardAggregation)(0),   // 0: minigames.LeaderboardAggregation
	(*StartSessionRequest)(nil),   // 1: minigames.StartSessionRequest
	(*Game)(nil),                  // 2: minigames.Game
	(*StartSessionResponse)(nil),  // 3: minigames.StartSessionResponse
	(*StopSessionRequest)(nil),    // 4: minigames.StopSessionRequest
	(*StopSessionResponse)(nil),   // 5: minigames.StopSessionResponse
	(*LeaderboardRequest)(nil),    // 6: minigames.LeaderboardRequest
	(*LeaderboardEntry)(nil),      // 7: minigames.LeaderboardEntry
	(*LeaderboardResponse)(nil),   // 8: minigames.LeaderboardResponse
	(*PlayerScoreRequest)(nil),    // 9: minigames.PlayerScoreRequest
	(*PlayerScoreResponse)(nil),   // 10: minigames.PlayerScoreResponse
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_minigames_minigames_proto_depIdxs = []int32{
	2,  // 0: minigames.StartSessionResponse.games:type_name -> minigames.Game
	11, // 1: minigames.LeaderboardRequest.from_time:type_name -> google.protobuf.Timestamp
	11, // 2: minigames.LeaderboardRequest.to_time:type_name -> google.protobuf.Timestamp
	0,  // 3: minigames.LeaderboardRequest.aggregation:type_name -> minigames.LeaderboardAggregation
	7,  // 4: minigames.LeaderboardResponse.entries:type_name -> minigames.LeaderboardEntry
	11, // 5: minigames.PlayerScoreRequest.from_time:type_name -> google.protobuf.Timestamp
	11, // 6: minigames.PlayerScoreRequest.to_time:type_name -> google.protobuf.Timestamp
	0,  // 7: minigames.PlayerScoreRequest.aggregation:type_name -> minigames.LeaderboardAggregation
	1,  // 8: minigames.Minigames.StartSession:input_type -> minigames.StartSessionRequest
	4,  // 9: minigames.Minigames.StopSession:input_type -> minigames.StopSessionRequest
	6,  // 10: minigames.Minigames.Leaderboard:input_type -> minigames.LeaderboardRequest
	9,  // 11: minigames.Minigames.PlayerScore:input_type -> minigames.PlayerScoreRequest
	3,  // 12: minigames.Minigames.StartSession:output_type -> minigames.StartSessionResponse
	5,  // 13: minigames.Minigames.StopSession:output_type -> minigames.StopSessionResponse
	8,  // 14: minigames.Minigames.Leaderboard:output_type -> minigames.LeaderboardResponse
	10, // 15: minigames.Minigames.PlayerScore:output_type -> minigames.PlayerScoreResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_minigames_minigames_proto_init() }
func file_minigames_minigames_proto_init() {
	if File_minigames_minigames_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_minigames_minigames_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_minigames_minigames_proto_goTypes,
		DependencyIndexes: file_minigames_minigames_proto_depIdxs,
		EnumInfos:         file_minigames_minigames_proto_enumTypes,
		MessageInfos:      file_minigames_minigames_proto_msgTypes,
	}.Build()
	File_minigames_minigames_proto = out.File
	file_minigames_minigames_proto_rawDesc = nil
	file_minigames_minigames_proto_goTypes = nil
	file_minigames_minigames_proto_depIdxs = nil
}
