// Code generated by protoc-gen-go-vtproto. DO NOT EDIT.
// protoc-gen-go-vtproto version: v0.6.1-0.20241121165744-79df5c4772f2
// source: minigames/minigames.proto

package minigames

import (
	proto "google.golang.org/protobuf/proto"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

func (this *StartSessionRequest) EqualVT(that *StartSessionRequest) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.BettingHandle != that.BettingHandle {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *StartSessionRequest) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*StartSessionRequest)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *Game) EqualVT(that *Game) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.Name != that.Name {
		return false
	}
	if this.AssetUrl != that.AssetUrl {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *Game) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*Game)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *StartSessionResponse) EqualVT(that *StartSessionResponse) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.PlayerUuid != that.PlayerUuid {
		return false
	}
	if this.SessionUuid != that.SessionUuid {
		return false
	}
	if len(this.Games) != len(that.Games) {
		return false
	}
	for i, vx := range this.Games {
		vy := that.Games[i]
		if p, q := vx, vy; p != q {
			if p == nil {
				p = &Game{}
			}
			if q == nil {
				q = &Game{}
			}
			if !p.EqualVT(q) {
				return false
			}
		}
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *StartSessionResponse) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*StartSessionResponse)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
