// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: minigames/minigames.proto

package minigames

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Minigames_StartSession_FullMethodName = "/minigames.Minigames/StartSession"
	Minigames_Leaderboard_FullMethodName  = "/minigames.Minigames/Leaderboard"
	Minigames_PlayerScore_FullMethodName  = "/minigames.Minigames/PlayerScore"
)

// MinigamesClient is the client API for Minigames service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MinigamesClient interface {
	// StartSession mints a stateless session token for the player and returns it
	// together with the player identifier and the per-client lobby URL (carrying
	// the token in its fragment). The lobby then lists games and reads
	// leaderboards over HTTP.
	StartSession(ctx context.Context, in *StartSessionRequest, opts ...grpc.CallOption) (*StartSessionResponse, error)
	// Leaderboard returns the client's top players by total score over a time
	// range, optionally for a single game.
	Leaderboard(ctx context.Context, in *LeaderboardRequest, opts ...grpc.CallOption) (*LeaderboardResponse, error)
	// PlayerScore returns one player's aggregated (sum or max) score over a time
	// range, identified by betting_handle.
	PlayerScore(ctx context.Context, in *PlayerScoreRequest, opts ...grpc.CallOption) (*PlayerScoreResponse, error)
}

type minigamesClient struct {
	cc grpc.ClientConnInterface
}

func NewMinigamesClient(cc grpc.ClientConnInterface) MinigamesClient {
	return &minigamesClient{cc}
}

func (c *minigamesClient) StartSession(ctx context.Context, in *StartSessionRequest, opts ...grpc.CallOption) (*StartSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartSessionResponse)
	err := c.cc.Invoke(ctx, Minigames_StartSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minigamesClient) Leaderboard(ctx context.Context, in *LeaderboardRequest, opts ...grpc.CallOption) (*LeaderboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaderboardResponse)
	err := c.cc.Invoke(ctx, Minigames_Leaderboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minigamesClient) PlayerScore(ctx context.Context, in *PlayerScoreRequest, opts ...grpc.CallOption) (*PlayerScoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlayerScoreResponse)
	err := c.cc.Invoke(ctx, Minigames_PlayerScore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MinigamesServer is the server API for Minigames service.
// All implementations must embed UnimplementedMinigamesServer
// for forward compatibility.
type MinigamesServer interface {
	// StartSession mints a stateless session token for the player and returns it
	// together with the player identifier and the per-client lobby URL (carrying
	// the token in its fragment). The lobby then lists games and reads
	// leaderboards over HTTP.
	StartSession(context.Context, *StartSessionRequest) (*StartSessionResponse, error)
	// Leaderboard returns the client's top players by total score over a time
	// range, optionally for a single game.
	Leaderboard(context.Context, *LeaderboardRequest) (*LeaderboardResponse, error)
	// PlayerScore returns one player's aggregated (sum or max) score over a time
	// range, identified by betting_handle.
	PlayerScore(context.Context, *PlayerScoreRequest) (*PlayerScoreResponse, error)
	mustEmbedUnimplementedMinigamesServer()
}

// UnimplementedMinigamesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMinigamesServer struct{}

func (UnimplementedMinigamesServer) StartSession(context.Context, *StartSessionRequest) (*StartSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartSession not implemented")
}
func (UnimplementedMinigamesServer) Leaderboard(context.Context, *LeaderboardRequest) (*LeaderboardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Leaderboard not implemented")
}
func (UnimplementedMinigamesServer) PlayerScore(context.Context, *PlayerScoreRequest) (*PlayerScoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlayerScore not implemented")
}
func (UnimplementedMinigamesServer) mustEmbedUnimplementedMinigamesServer() {}
func (UnimplementedMinigamesServer) testEmbeddedByValue()                   {}

// UnsafeMinigamesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MinigamesServer will
// result in compilation errors.
type UnsafeMinigamesServer interface {
	mustEmbedUnimplementedMinigamesServer()
}

func RegisterMinigamesServer(s grpc.ServiceRegistrar, srv MinigamesServer) {
	// If the following call pancis, it indicates UnimplementedMinigamesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Minigames_ServiceDesc, srv)
}

func _Minigames_StartSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinigamesServer).StartSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Minigames_StartSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinigamesServer).StartSession(ctx, req.(*StartSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Minigames_Leaderboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaderboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinigamesServer).Leaderboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Minigames_Leaderboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinigamesServer).Leaderboard(ctx, req.(*LeaderboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Minigames_PlayerScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinigamesServer).PlayerScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Minigames_PlayerScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinigamesServer).PlayerScore(ctx, req.(*PlayerScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Minigames_ServiceDesc is the grpc.ServiceDesc for Minigames service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Minigames_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "minigames.Minigames",
	HandlerType: (*MinigamesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartSession",
			Handler:    _Minigames_StartSession_Handler,
		},
		{
			MethodName: "Leaderboard",
			Handler:    _Minigames_Leaderboard_Handler,
		},
		{
			MethodName: "PlayerScore",
			Handler:    _Minigames_PlayerScore_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "minigames/minigames.proto",
}
