// Code generated by protoc-gen-go-vtproto. DO NOT EDIT.
// protoc-gen-go-vtproto version: v0.6.1-0.20241121165744-79df5c4772f2
// source: minigames/minigames.proto

package minigames

import (
	timestamppb "github.com/planetscale/vtprotobuf/types/known/timestamppb"
	proto "google.golang.org/protobuf/proto"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

func (this *StartSessionRequest) EqualVT(that *StartSessionRequest) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.BettingHandle != that.BettingHandle {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *StartSessionRequest) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*StartSessionRequest)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *Game) EqualVT(that *Game) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.Name != that.Name {
		return false
	}
	if this.AssetUrl != that.AssetUrl {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *Game) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*Game)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *StartSessionResponse) EqualVT(that *StartSessionResponse) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.PlayerUuid != that.PlayerUuid {
		return false
	}
	if this.SessionToken != that.SessionToken {
		return false
	}
	if len(this.Games) != len(that.Games) {
		return false
	}
	for i, vx := range this.Games {
		vy := that.Games[i]
		if p, q := vx, vy; p != q {
			if p == nil {
				p = &Game{}
			}
			if q == nil {
				q = &Game{}
			}
			if !p.EqualVT(q) {
				return false
			}
		}
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *StartSessionResponse) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*StartSessionResponse)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *StopSessionRequest) EqualVT(that *StopSessionRequest) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.BettingHandle != that.BettingHandle {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *StopSessionRequest) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*StopSessionRequest)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *StopSessionResponse) EqualVT(that *StopSessionResponse) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *StopSessionResponse) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*StopSessionResponse)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *LeaderboardRequest) EqualVT(that *LeaderboardRequest) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.GameSlug != that.GameSlug {
		return false
	}
	if !(*timestamppb.Timestamp)(this.FromTime).EqualVT((*timestamppb.Timestamp)(that.FromTime)) {
		return false
	}
	if !(*timestamppb.Timestamp)(this.ToTime).EqualVT((*timestamppb.Timestamp)(that.ToTime)) {
		return false
	}
	if this.Limit != that.Limit {
		return false
	}
	if this.Aggregation != that.Aggregation {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *LeaderboardRequest) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*LeaderboardRequest)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *LeaderboardEntry) EqualVT(that *LeaderboardEntry) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.PlayerUuid != that.PlayerUuid {
		return false
	}
	if this.BettingHandle != that.BettingHandle {
		return false
	}
	if this.TotalScore != that.TotalScore {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *LeaderboardEntry) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*LeaderboardEntry)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *LeaderboardResponse) EqualVT(that *LeaderboardResponse) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if len(this.Entries) != len(that.Entries) {
		return false
	}
	for i, vx := range this.Entries {
		vy := that.Entries[i]
		if p, q := vx, vy; p != q {
			if p == nil {
				p = &LeaderboardEntry{}
			}
			if q == nil {
				q = &LeaderboardEntry{}
			}
			if !p.EqualVT(q) {
				return false
			}
		}
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *LeaderboardResponse) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*LeaderboardResponse)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *PlayerScoreRequest) EqualVT(that *PlayerScoreRequest) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.BettingHandle != that.BettingHandle {
		return false
	}
	if !(*timestamppb.Timestamp)(this.FromTime).EqualVT((*timestamppb.Timestamp)(that.FromTime)) {
		return false
	}
	if !(*timestamppb.Timestamp)(this.ToTime).EqualVT((*timestamppb.Timestamp)(that.ToTime)) {
		return false
	}
	if this.Aggregation != that.Aggregation {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *PlayerScoreRequest) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*PlayerScoreRequest)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *PlayerScoreResponse) EqualVT(that *PlayerScoreResponse) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.TotalScore != that.TotalScore {
		return false
	}
	if this.Found != that.Found {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *PlayerScoreResponse) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*PlayerScoreResponse)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
