// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v3.21.12
// source: ghost/ghost.proto

package ghost

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MatchStatus int32

const (
	MatchStatus_MATCH_STATUS_UNKNOWN     MatchStatus = 0
	MatchStatus_MATCH_STATUS_AVAILABLE   MatchStatus = 1
	MatchStatus_MATCH_STATUS_UNAVAILABLE MatchStatus = 2
)

// Enum value maps for MatchStatus.
var (
	MatchStatus_name = map[int32]string{
		0: "MATCH_STATUS_UNKNOWN",
		1: "MATCH_STATUS_AVAILABLE",
		2: "MATCH_STATUS_UNAVAILABLE",
	}
	MatchStatus_value = map[string]int32{
		"MATCH_STATUS_UNKNOWN":     0,
		"MATCH_STATUS_AVAILABLE":   1,
		"MATCH_STATUS_UNAVAILABLE": 2,
	}
)

func (x MatchStatus) Enum() *MatchStatus {
	p := new(MatchStatus)
	*p = x
	return p
}

func (x MatchStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_ghost_ghost_proto_enumTypes[0].Descriptor()
}

func (MatchStatus) Type() protoreflect.EnumType {
	return &file_ghost_ghost_proto_enumTypes[0]
}

func (x MatchStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchStatus.Descriptor instead.
func (MatchStatus) EnumDescriptor() ([]byte, []int) {
	return file_ghost_ghost_proto_rawDescGZIP(), []int{0}
}

type FeedbackType int32

const (
	FeedbackType_FEEDBACK_TYPE_UNKNOWN    FeedbackType = 0
	FeedbackType_FEEDBACK_TYPE_BUG        FeedbackType = 1
	FeedbackType_FEEDBACK_TYPE_SUGGESTION FeedbackType = 2
)

// Enum value maps for FeedbackType.
var (
	FeedbackType_name = map[int32]string{
		0: "FEEDBACK_TYPE_UNKNOWN",
		1: "FEEDBACK_TYPE_BUG",
		2: "FEEDBACK_TYPE_SUGGESTION",
	}
	FeedbackType_value = map[string]int32{
		"FEEDBACK_TYPE_UNKNOWN":    0,
		"FEEDBACK_TYPE_BUG":        1,
		"FEEDBACK_TYPE_SUGGESTION": 2,
	}
)

func (x FeedbackType) Enum() *FeedbackType {
	p := new(FeedbackType)
	*p = x
	return p
}

func (x FeedbackType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FeedbackType) Descriptor() protoreflect.EnumDescriptor {
	return file_ghost_ghost_proto_enumTypes[1].Descriptor()
}

func (FeedbackType) Type() protoreflect.EnumType {
	return &file_ghost_ghost_proto_enumTypes[1]
}

func (x FeedbackType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FeedbackType.Descriptor instead.
func (FeedbackType) EnumDescriptor() ([]byte, []int) {
	return file_ghost_ghost_proto_rawDescGZIP(), []int{1}
}

type MatchInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchUrn      string                 `protobuf:"bytes,1,opt,name=match_urn,json=matchUrn,proto3" json:"match_urn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchInfoRequest) Reset() {
	*x = MatchInfoRequest{}
	mi := &file_ghost_ghost_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchInfoRequest) ProtoMessage() {}

func (x *MatchInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ghost_ghost_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchInfoRequest.ProtoReflect.Descriptor instead.
func (*MatchInfoRequest) Descriptor() ([]byte, []int) {
	return file_ghost_ghost_proto_rawDescGZIP(), []int{0}
}

func (x *MatchInfoRequest) GetMatchUrn() string {
	if x != nil {
		return x.MatchUrn
	}
	return ""
}

type MatchInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to MatchInfo:
	//
	//	*MatchInfoResponse_Cs2
	//	*MatchInfoResponse_Dota2
	MatchInfo     isMatchInfoResponse_MatchInfo `protobuf_oneof:"match_info"`
	Host          string                        `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchInfoResponse) Reset() {
	*x = MatchInfoResponse{}
	mi := &file_ghost_ghost_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchInfoResponse) ProtoMessage() {}

func (x *MatchInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ghost_ghost_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchInfoResponse.ProtoReflect.Descriptor instead.
func (*MatchInfoResponse) Descriptor() ([]byte, []int) {
	return file_ghost_ghost_proto_rawDescGZIP(), []int{1}
}

func (x *MatchInfoResponse) GetMatchInfo() isMatchInfoResponse_MatchInfo {
	if x != nil {
		return x.MatchInfo
	}
	return nil
}

func (x *MatchInfoResponse) GetCs2() *CS2MatchInfoResponse {
	if x != nil {
		if x, ok := x.MatchInfo.(*MatchInfoResponse_Cs2); ok {
			return x.Cs2
		}
	}
	return nil
}

func (x *MatchInfoResponse) GetDota2() *Dota2MatchInfoResponse {
	if x != nil {
		if x, ok := x.MatchInfo.(*MatchInfoResponse_Dota2); ok {
			return x.Dota2
		}
	}
	return nil
}

func (x *MatchInfoResponse) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

type isMatchInfoResponse_MatchInfo interface {
	isMatchInfoResponse_MatchInfo()
}

type MatchInfoResponse_Cs2 struct {
	Cs2 *CS2MatchInfoResponse `protobuf:"bytes,1,opt,name=cs2,proto3,oneof"`
}

type MatchInfoResponse_Dota2 struct {
	Dota2 *Dota2MatchInfoResponse `protobuf:"bytes,2,opt,name=dota2,proto3,oneof"`
}

func (*MatchInfoResponse_Cs2) isMatchInfoResponse_MatchInfo() {}

func (*MatchInfoResponse_Dota2) isMatchInfoResponse_MatchInfo() {}

type CS2MatchInfoResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	MapName      string                 `protobuf:"bytes,2,opt,name=map_name,json=mapName,proto3" json:"map_name,omitempty"`
	MapAssetName string                 `protobuf:"bytes,3,opt,name=map_asset_name,json=mapAssetName,proto3" json:"map_asset_name,omitempty"`
	GameVersion  string                 `protobuf:"bytes,4,opt,name=game_version,json=gameVersion,proto3" json:"game_version,omitempty"`
	// Specifies the URL for the asset of the match.
	AssetUrl      string `protobuf:"bytes,5,opt,name=asset_url,json=assetUrl,proto3" json:"asset_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CS2MatchInfoResponse) Reset() {
	*x = CS2MatchInfoResponse{}
	mi := &file_ghost_ghost_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CS2MatchInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS2MatchInfoResponse) ProtoMessage() {}

func (x *CS2MatchInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ghost_ghost_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS2MatchInfoResponse.ProtoReflect.Descriptor instead.
func (*CS2MatchInfoResponse) Descriptor() ([]byte, []int) {
	return file_ghost_ghost_proto_rawDescGZIP(), []int{2}
}

func (x *CS2MatchInfoResponse) GetMapName() string {
	if x != nil {
		return x.MapName
	}
	return ""
}

func (x *CS2MatchInfoResponse) GetMapAssetName() string {
	if x != nil {
		return x.MapAssetName
	}
	return ""
}

func (x *CS2MatchInfoResponse) GetGameVersion() string {
	if x != nil {
		return x.GameVersion
	}
	return ""
}

func (x *CS2MatchInfoResponse) GetAssetUrl() string {
	if x != nil {
		return x.AssetUrl
	}
	return ""
}

type Dota2MatchInfoResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	GameVersion string                 `protobuf:"bytes,2,opt,name=game_version,json=gameVersion,proto3" json:"game_version,omitempty"`
	// Specifies the URL for the asset of the match.
	AssetUrl      string `protobuf:"bytes,3,opt,name=asset_url,json=assetUrl,proto3" json:"asset_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dota2MatchInfoResponse) Reset() {
	*x = Dota2MatchInfoResponse{}
	mi := &file_ghost_ghost_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dota2MatchInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dota2MatchInfoResponse) ProtoMessage() {}

func (x *Dota2MatchInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ghost_ghost_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dota2MatchInfoResponse.ProtoReflect.Descriptor instead.
func (*Dota2MatchInfoResponse) Descriptor() ([]byte, []int) {
	return file_ghost_ghost_proto_rawDescGZIP(), []int{3}
}

func (x *Dota2MatchInfoResponse) GetGameVersion() string {
	if x != nil {
		return x.GameVersion
	}
	return ""
}

func (x *Dota2MatchInfoResponse) GetAssetUrl() string {
	if x != nil {
		return x.AssetUrl
	}
	return ""
}

type MatchStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchUrn      string                 `protobuf:"bytes,1,opt,name=match_urn,json=matchUrn,proto3" json:"match_urn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchStatusRequest) Reset() {
	*x = MatchStatusRequest{}
	mi := &file_ghost_ghost_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchStatusRequest) ProtoMessage() {}

func (x *MatchStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ghost_ghost_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchStatusRequest.ProtoReflect.Descriptor instead.
func (*MatchStatusRequest) Descriptor() ([]byte, []int) {
	return file_ghost_ghost_proto_rawDescGZIP(), []int{4}
}

func (x *MatchStatusRequest) GetMatchUrn() string {
	if x != nil {
		return x.MatchUrn
	}
	return ""
}

type MatchStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchStatus   MatchStatus            `protobuf:"varint,1,opt,name=match_status,json=matchStatus,proto3,enum=ghost.MatchStatus" json:"match_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchStatusResponse) Reset() {
	*x = MatchStatusResponse{}
	mi := &file_ghost_ghost_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchStatusResponse) ProtoMessage() {}

func (x *MatchStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ghost_ghost_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchStatusResponse.ProtoReflect.Descriptor instead.
func (*MatchStatusResponse) Descriptor() ([]byte, []int) {
	return file_ghost_ghost_proto_rawDescGZIP(), []int{5}
}

func (x *MatchStatusResponse) GetMatchStatus() MatchStatus {
	if x != nil {
		return x.MatchStatus
	}
	return MatchStatus_MATCH_STATUS_UNKNOWN
}

type FeedbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedbackType  FeedbackType           `protobuf:"varint,1,opt,name=feedback_type,json=feedbackType,proto3,enum=ghost.FeedbackType" json:"feedback_type,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Email         *string                `protobuf:"bytes,3,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Attachments   []*FeedbackAttachment  `protobuf:"bytes,4,rep,name=attachments,proto3" json:"attachments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedbackRequest) Reset() {
	*x = FeedbackRequest{}
	mi := &file_ghost_ghost_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedbackRequest) ProtoMessage() {}

func (x *FeedbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ghost_ghost_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedbackRequest.ProtoReflect.Descriptor instead.
func (*FeedbackRequest) Descriptor() ([]byte, []int) {
	return file_ghost_ghost_proto_rawDescGZIP(), []int{6}
}

func (x *FeedbackRequest) GetFeedbackType() FeedbackType {
	if x != nil {
		return x.FeedbackType
	}
	return FeedbackType_FEEDBACK_TYPE_UNKNOWN
}

func (x *FeedbackRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FeedbackRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *FeedbackRequest) GetAttachments() []*FeedbackAttachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

type FeedbackAttachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // e.g., "application/pdf"
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`                                  // raw file bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedbackAttachment) Reset() {
	*x = FeedbackAttachment{}
	mi := &file_ghost_ghost_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedbackAttachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedbackAttachment) ProtoMessage() {}

func (x *FeedbackAttachment) ProtoReflect() protoreflect.Message {
	mi := &file_ghost_ghost_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedbackAttachment.ProtoReflect.Descriptor instead.
func (*FeedbackAttachment) Descriptor() ([]byte, []int) {
	return file_ghost_ghost_proto_rawDescGZIP(), []int{7}
}

func (x *FeedbackAttachment) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *FeedbackAttachment) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type FeedbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedbackResponse) Reset() {
	*x = FeedbackResponse{}
	mi := &file_ghost_ghost_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedbackResponse) ProtoMessage() {}

func (x *FeedbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ghost_ghost_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedbackResponse.ProtoReflect.Descriptor instead.
func (*FeedbackResponse) Descriptor() ([]byte, []int) {
	return file_ghost_ghost_proto_rawDescGZIP(), []int{8}
}

var File_ghost_ghost_proto protoreflect.FileDescriptor

var file_ghost_ghost_proto_rawDesc = []byte{
	0x0a, 0x11, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x2f, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x22, 0x2f, 0x0a, 0x10, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b,
	0x0a, 0x09, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x75, 0x72, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x55, 0x72, 0x6e, 0x22, 0x9d, 0x01, 0x0a, 0x11,
	0x4d, 0x61, 0x74, 0x63, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2f, 0x0a, 0x03, 0x63, 0x73, 0x32, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x2e, 0x43, 0x53, 0x32, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x03, 0x63,
	0x73, 0x32, 0x12, 0x35, 0x0a, 0x05, 0x64, 0x6f, 0x74, 0x61, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1d, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x2e, 0x44, 0x6f, 0x74, 0x61, 0x32, 0x4d,
	0x61, 0x74, 0x63, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x48, 0x00, 0x52, 0x05, 0x64, 0x6f, 0x74, 0x61, 0x32, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x42, 0x0c, 0x0a,
	0x0a, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x97, 0x01, 0x0a, 0x14,
	0x43, 0x53, 0x32, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x61, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x61, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x24, 0x0a, 0x0e, 0x6d, 0x61, 0x70, 0x5f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d, 0x61, 0x70, 0x41, 0x73, 0x73, 0x65,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x67, 0x61, 0x6d,
	0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x73, 0x73, 0x65,
	0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x73, 0x73,
	0x65, 0x74, 0x55, 0x72, 0x6c, 0x22, 0x58, 0x0a, 0x16, 0x44, 0x6f, 0x74, 0x61, 0x32, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x21, 0x0a, 0x0c, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x67, 0x61, 0x6d, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x73, 0x73, 0x65, 0x74, 0x55, 0x72, 0x6c, 0x22,
	0x31, 0x0a, 0x12, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x75,
	0x72, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x55,
	0x72, 0x6e, 0x22, 0x4c, 0x0a, 0x13, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0c, 0x6d, 0x61, 0x74,
	0x63, 0x68, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x12, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x0b, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0xcf, 0x01, 0x0a, 0x0f, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x0d, 0x66, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x67, 0x68,
	0x6f, 0x73, 0x74, 0x2e, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x0c, 0x66, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x19, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x88, 0x01, 0x01, 0x12, 0x3b, 0x0a, 0x0b, 0x61,
	0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x2e, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63,
	0x6b, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0b, 0x61, 0x74, 0x74,
	0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x22, 0x4b, 0x0a, 0x12, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x41, 0x74,
	0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x12, 0x0a, 0x10, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2a, 0x61, 0x0a, 0x0b, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x18, 0x0a, 0x14, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x55, 0x53, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x1a, 0x0a, 0x16,
	0x4d, 0x41, 0x54, 0x43, 0x48, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x41, 0x56, 0x41,
	0x49, 0x4c, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x1c, 0x0a, 0x18, 0x4d, 0x41, 0x54, 0x43,
	0x48, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x41, 0x56, 0x41, 0x49, 0x4c,
	0x41, 0x42, 0x4c, 0x45, 0x10, 0x02, 0x2a, 0x5e, 0x0a, 0x0c, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61,
	0x63, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x15, 0x46, 0x45, 0x45, 0x44, 0x42, 0x41,
	0x43, 0x4b, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10,
	0x00, 0x12, 0x15, 0x0a, 0x11, 0x46, 0x45, 0x45, 0x44, 0x42, 0x41, 0x43, 0x4b, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x42, 0x55, 0x47, 0x10, 0x01, 0x12, 0x1c, 0x0a, 0x18, 0x46, 0x45, 0x45, 0x44,
	0x42, 0x41, 0x43, 0x4b, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x55, 0x47, 0x47, 0x45, 0x53,
	0x54, 0x49, 0x4f, 0x4e, 0x10, 0x02, 0x32, 0xd4, 0x01, 0x0a, 0x05, 0x47, 0x68, 0x6f, 0x73, 0x74,
	0x12, 0x41, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x17, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x67, 0x68, 0x6f, 0x73,
	0x74, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x19, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x2e, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x0c,
	0x53, 0x65, 0x6e, 0x64, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x12, 0x16, 0x2e, 0x67,
	0x68, 0x6f, 0x73, 0x74, 0x2e, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x2e, 0x46, 0x65, 0x65,
	0x64, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x21, 0x0a,
	0x0f, 0x63, 0x6f, 0x6d, 0x2e, 0x6f, 0x64, 0x64, 0x69, 0x6e, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74,
	0x5a, 0x0e, 0x6f, 0x64, 0x64, 0x69, 0x6e, 0x2e, 0x67, 0x67, 0x2f, 0x67, 0x68, 0x6f, 0x73, 0x74,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ghost_ghost_proto_rawDescOnce sync.Once
	file_ghost_ghost_proto_rawDescData = file_ghost_ghost_proto_rawDesc
)

func file_ghost_ghost_proto_rawDescGZIP() []byte {
	file_ghost_ghost_proto_rawDescOnce.Do(func() {
		file_ghost_ghost_proto_rawDescData = protoimpl.X.CompressGZIP(file_ghost_ghost_proto_rawDescData)
	})
	return file_ghost_ghost_proto_rawDescData
}

var file_ghost_ghost_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_ghost_ghost_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_ghost_ghost_proto_goTypes = []any{
	(MatchStatus)(0),               // 0: ghost.MatchStatus
	(FeedbackType)(0),              // 1: ghost.FeedbackType
	(*MatchInfoRequest)(nil),       // 2: ghost.MatchInfoRequest
	(*MatchInfoResponse)(nil),      // 3: ghost.MatchInfoResponse
	(*CS2MatchInfoResponse)(nil),   // 4: ghost.CS2MatchInfoResponse
	(*Dota2MatchInfoResponse)(nil), // 5: ghost.Dota2MatchInfoResponse
	(*MatchStatusRequest)(nil),     // 6: ghost.MatchStatusRequest
	(*MatchStatusResponse)(nil),    // 7: ghost.MatchStatusResponse
	(*FeedbackRequest)(nil),        // 8: ghost.FeedbackRequest
	(*FeedbackAttachment)(nil),     // 9: ghost.FeedbackAttachment
	(*FeedbackResponse)(nil),       // 10: ghost.FeedbackResponse
}
var file_ghost_ghost_proto_depIdxs = []int32{
	4,  // 0: ghost.MatchInfoResponse.cs2:type_name -> ghost.CS2MatchInfoResponse
	5,  // 1: ghost.MatchInfoResponse.dota2:type_name -> ghost.Dota2MatchInfoResponse
	0,  // 2: ghost.MatchStatusResponse.match_status:type_name -> ghost.MatchStatus
	1,  // 3: ghost.FeedbackRequest.feedback_type:type_name -> ghost.FeedbackType
	9,  // 4: ghost.FeedbackRequest.attachments:type_name -> ghost.FeedbackAttachment
	2,  // 5: ghost.Ghost.GetMatchInfo:input_type -> ghost.MatchInfoRequest
	6,  // 6: ghost.Ghost.GetMatchStatus:input_type -> ghost.MatchStatusRequest
	8,  // 7: ghost.Ghost.SendFeedback:input_type -> ghost.FeedbackRequest
	3,  // 8: ghost.Ghost.GetMatchInfo:output_type -> ghost.MatchInfoResponse
	7,  // 9: ghost.Ghost.GetMatchStatus:output_type -> ghost.MatchStatusResponse
	10, // 10: ghost.Ghost.SendFeedback:output_type -> ghost.FeedbackResponse
	8,  // [8:11] is the sub-list for method output_type
	5,  // [5:8] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_ghost_ghost_proto_init() }
func file_ghost_ghost_proto_init() {
	if File_ghost_ghost_proto != nil {
		return
	}
	file_ghost_ghost_proto_msgTypes[1].OneofWrappers = []any{
		(*MatchInfoResponse_Cs2)(nil),
		(*MatchInfoResponse_Dota2)(nil),
	}
	file_ghost_ghost_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ghost_ghost_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ghost_ghost_proto_goTypes,
		DependencyIndexes: file_ghost_ghost_proto_depIdxs,
		EnumInfos:         file_ghost_ghost_proto_enumTypes,
		MessageInfos:      file_ghost_ghost_proto_msgTypes,
	}.Build()
	File_ghost_ghost_proto = out.File
	file_ghost_ghost_proto_rawDesc = nil
	file_ghost_ghost_proto_goTypes = nil
	file_ghost_ghost_proto_depIdxs = nil
}
