// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v3.21.12
// source: ghost/ghost.proto

package ghost

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MatchStatus int32

const (
	MatchStatus_MATCH_STATUS_UNKNOWN     MatchStatus = 0
	MatchStatus_MATCH_STATUS_AVAILABLE   MatchStatus = 1
	MatchStatus_MATCH_STATUS_UNAVAILABLE MatchStatus = 2
)

// Enum value maps for MatchStatus.
var (
	MatchStatus_name = map[int32]string{
		0: "MATCH_STATUS_UNKNOWN",
		1: "MATCH_STATUS_AVAILABLE",
		2: "MATCH_STATUS_UNAVAILABLE",
	}
	MatchStatus_value = map[string]int32{
		"MATCH_STATUS_UNKNOWN":     0,
		"MATCH_STATUS_AVAILABLE":   1,
		"MATCH_STATUS_UNAVAILABLE": 2,
	}
)

func (x MatchStatus) Enum() *MatchStatus {
	p := new(MatchStatus)
	*p = x
	return p
}

func (x MatchStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_ghost_ghost_proto_enumTypes[0].Descriptor()
}

func (MatchStatus) Type() protoreflect.EnumType {
	return &file_ghost_ghost_proto_enumTypes[0]
}

func (x MatchStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchStatus.Descriptor instead.
func (MatchStatus) EnumDescriptor() ([]byte, []int) {
	return file_ghost_ghost_proto_rawDescGZIP(), []int{0}
}

type MatchInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchUrn      string                 `protobuf:"bytes,1,opt,name=match_urn,json=matchUrn,proto3" json:"match_urn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchInfoRequest) Reset() {
	*x = MatchInfoRequest{}
	mi := &file_ghost_ghost_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchInfoRequest) ProtoMessage() {}

func (x *MatchInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ghost_ghost_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchInfoRequest.ProtoReflect.Descriptor instead.
func (*MatchInfoRequest) Descriptor() ([]byte, []int) {
	return file_ghost_ghost_proto_rawDescGZIP(), []int{0}
}

func (x *MatchInfoRequest) GetMatchUrn() string {
	if x != nil {
		return x.MatchUrn
	}
	return ""
}

type MatchInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to MatchInfo:
	//
	//	*MatchInfoResponse_Cs2
	//	*MatchInfoResponse_Dota2
	MatchInfo     isMatchInfoResponse_MatchInfo `protobuf_oneof:"match_info"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchInfoResponse) Reset() {
	*x = MatchInfoResponse{}
	mi := &file_ghost_ghost_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchInfoResponse) ProtoMessage() {}

func (x *MatchInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ghost_ghost_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchInfoResponse.ProtoReflect.Descriptor instead.
func (*MatchInfoResponse) Descriptor() ([]byte, []int) {
	return file_ghost_ghost_proto_rawDescGZIP(), []int{1}
}

func (x *MatchInfoResponse) GetMatchInfo() isMatchInfoResponse_MatchInfo {
	if x != nil {
		return x.MatchInfo
	}
	return nil
}

func (x *MatchInfoResponse) GetCs2() *CS2MatchInfoResponse {
	if x != nil {
		if x, ok := x.MatchInfo.(*MatchInfoResponse_Cs2); ok {
			return x.Cs2
		}
	}
	return nil
}

func (x *MatchInfoResponse) GetDota2() *Dota2MatchInfoResponse {
	if x != nil {
		if x, ok := x.MatchInfo.(*MatchInfoResponse_Dota2); ok {
			return x.Dota2
		}
	}
	return nil
}

type isMatchInfoResponse_MatchInfo interface {
	isMatchInfoResponse_MatchInfo()
}

type MatchInfoResponse_Cs2 struct {
	Cs2 *CS2MatchInfoResponse `protobuf:"bytes,1,opt,name=cs2,proto3,oneof"`
}

type MatchInfoResponse_Dota2 struct {
	Dota2 *Dota2MatchInfoResponse `protobuf:"bytes,2,opt,name=dota2,proto3,oneof"`
}

func (*MatchInfoResponse_Cs2) isMatchInfoResponse_MatchInfo() {}

func (*MatchInfoResponse_Dota2) isMatchInfoResponse_MatchInfo() {}

type CS2MatchInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MapName       string                 `protobuf:"bytes,2,opt,name=map_name,json=mapName,proto3" json:"map_name,omitempty"`
	MapAssetName  string                 `protobuf:"bytes,3,opt,name=map_asset_name,json=mapAssetName,proto3" json:"map_asset_name,omitempty"`
	GameVersion   string                 `protobuf:"bytes,4,opt,name=game_version,json=gameVersion,proto3" json:"game_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CS2MatchInfoResponse) Reset() {
	*x = CS2MatchInfoResponse{}
	mi := &file_ghost_ghost_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CS2MatchInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS2MatchInfoResponse) ProtoMessage() {}

func (x *CS2MatchInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ghost_ghost_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS2MatchInfoResponse.ProtoReflect.Descriptor instead.
func (*CS2MatchInfoResponse) Descriptor() ([]byte, []int) {
	return file_ghost_ghost_proto_rawDescGZIP(), []int{2}
}

func (x *CS2MatchInfoResponse) GetMapName() string {
	if x != nil {
		return x.MapName
	}
	return ""
}

func (x *CS2MatchInfoResponse) GetMapAssetName() string {
	if x != nil {
		return x.MapAssetName
	}
	return ""
}

func (x *CS2MatchInfoResponse) GetGameVersion() string {
	if x != nil {
		return x.GameVersion
	}
	return ""
}

type Dota2MatchInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameVersion   string                 `protobuf:"bytes,2,opt,name=game_version,json=gameVersion,proto3" json:"game_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dota2MatchInfoResponse) Reset() {
	*x = Dota2MatchInfoResponse{}
	mi := &file_ghost_ghost_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dota2MatchInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dota2MatchInfoResponse) ProtoMessage() {}

func (x *Dota2MatchInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ghost_ghost_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dota2MatchInfoResponse.ProtoReflect.Descriptor instead.
func (*Dota2MatchInfoResponse) Descriptor() ([]byte, []int) {
	return file_ghost_ghost_proto_rawDescGZIP(), []int{3}
}

func (x *Dota2MatchInfoResponse) GetGameVersion() string {
	if x != nil {
		return x.GameVersion
	}
	return ""
}

type MatchStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchUrn      string                 `protobuf:"bytes,1,opt,name=match_urn,json=matchUrn,proto3" json:"match_urn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchStatusRequest) Reset() {
	*x = MatchStatusRequest{}
	mi := &file_ghost_ghost_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchStatusRequest) ProtoMessage() {}

func (x *MatchStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ghost_ghost_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchStatusRequest.ProtoReflect.Descriptor instead.
func (*MatchStatusRequest) Descriptor() ([]byte, []int) {
	return file_ghost_ghost_proto_rawDescGZIP(), []int{4}
}

func (x *MatchStatusRequest) GetMatchUrn() string {
	if x != nil {
		return x.MatchUrn
	}
	return ""
}

type MatchStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchStatus   MatchStatus            `protobuf:"varint,1,opt,name=match_status,json=matchStatus,proto3,enum=ghost.MatchStatus" json:"match_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchStatusResponse) Reset() {
	*x = MatchStatusResponse{}
	mi := &file_ghost_ghost_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchStatusResponse) ProtoMessage() {}

func (x *MatchStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ghost_ghost_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchStatusResponse.ProtoReflect.Descriptor instead.
func (*MatchStatusResponse) Descriptor() ([]byte, []int) {
	return file_ghost_ghost_proto_rawDescGZIP(), []int{5}
}

func (x *MatchStatusResponse) GetMatchStatus() MatchStatus {
	if x != nil {
		return x.MatchStatus
	}
	return MatchStatus_MATCH_STATUS_UNKNOWN
}

var File_ghost_ghost_proto protoreflect.FileDescriptor

var file_ghost_ghost_proto_rawDesc = []byte{
	0x0a, 0x11, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x2f, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x22, 0x2f, 0x0a, 0x10, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b,
	0x0a, 0x09, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x75, 0x72, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x55, 0x72, 0x6e, 0x22, 0x89, 0x01, 0x0a, 0x11,
	0x4d, 0x61, 0x74, 0x63, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2f, 0x0a, 0x03, 0x63, 0x73, 0x32, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x2e, 0x43, 0x53, 0x32, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x03, 0x63,
	0x73, 0x32, 0x12, 0x35, 0x0a, 0x05, 0x64, 0x6f, 0x74, 0x61, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1d, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x2e, 0x44, 0x6f, 0x74, 0x61, 0x32, 0x4d,
	0x61, 0x74, 0x63, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x48, 0x00, 0x52, 0x05, 0x64, 0x6f, 0x74, 0x61, 0x32, 0x42, 0x0c, 0x0a, 0x0a, 0x6d, 0x61, 0x74,
	0x63, 0x68, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x7a, 0x0a, 0x14, 0x43, 0x53, 0x32, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x19, 0x0a, 0x08, 0x6d, 0x61, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x61, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x6d, 0x61,
	0x70, 0x5f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x6d, 0x61, 0x70, 0x41, 0x73, 0x73, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x21, 0x0a, 0x0c, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x67, 0x61, 0x6d, 0x65, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x22, 0x3b, 0x0a, 0x16, 0x44, 0x6f, 0x74, 0x61, 0x32, 0x4d, 0x61, 0x74, 0x63,
	0x68, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a,
	0x0c, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x67, 0x61, 0x6d, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x22, 0x31, 0x0a, 0x12, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f,
	0x75, 0x72, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x61, 0x74, 0x63, 0x68,
	0x55, 0x72, 0x6e, 0x22, 0x4c, 0x0a, 0x13, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0c, 0x6d, 0x61,
	0x74, 0x63, 0x68, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x12, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x0b, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x2a, 0x61, 0x0a, 0x0b, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x18, 0x0a, 0x14, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53,
	0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x1a, 0x0a, 0x16, 0x4d, 0x41,
	0x54, 0x43, 0x48, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x41, 0x56, 0x41, 0x49, 0x4c,
	0x41, 0x42, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x1c, 0x0a, 0x18, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x41, 0x56, 0x41, 0x49, 0x4c, 0x41, 0x42,
	0x4c, 0x45, 0x10, 0x02, 0x32, 0x93, 0x01, 0x0a, 0x05, 0x47, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x41,
	0x0a, 0x0c, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17,
	0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x2e,
	0x4d, 0x61, 0x74, 0x63, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x47, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x19, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x2e, 0x4d, 0x61, 0x74, 0x63,
	0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a,
	0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x21, 0x0a, 0x0f, 0x63, 0x6f,
	0x6d, 0x2e, 0x6f, 0x64, 0x64, 0x69, 0x6e, 0x2e, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x5a, 0x0e, 0x6f,
	0x64, 0x64, 0x69, 0x6e, 0x2e, 0x67, 0x67, 0x2f, 0x67, 0x68, 0x6f, 0x73, 0x74, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ghost_ghost_proto_rawDescOnce sync.Once
	file_ghost_ghost_proto_rawDescData = file_ghost_ghost_proto_rawDesc
)

func file_ghost_ghost_proto_rawDescGZIP() []byte {
	file_ghost_ghost_proto_rawDescOnce.Do(func() {
		file_ghost_ghost_proto_rawDescData = protoimpl.X.CompressGZIP(file_ghost_ghost_proto_rawDescData)
	})
	return file_ghost_ghost_proto_rawDescData
}

var file_ghost_ghost_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ghost_ghost_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_ghost_ghost_proto_goTypes = []any{
	(MatchStatus)(0),               // 0: ghost.MatchStatus
	(*MatchInfoRequest)(nil),       // 1: ghost.MatchInfoRequest
	(*MatchInfoResponse)(nil),      // 2: ghost.MatchInfoResponse
	(*CS2MatchInfoResponse)(nil),   // 3: ghost.CS2MatchInfoResponse
	(*Dota2MatchInfoResponse)(nil), // 4: ghost.Dota2MatchInfoResponse
	(*MatchStatusRequest)(nil),     // 5: ghost.MatchStatusRequest
	(*MatchStatusResponse)(nil),    // 6: ghost.MatchStatusResponse
}
var file_ghost_ghost_proto_depIdxs = []int32{
	3, // 0: ghost.MatchInfoResponse.cs2:type_name -> ghost.CS2MatchInfoResponse
	4, // 1: ghost.MatchInfoResponse.dota2:type_name -> ghost.Dota2MatchInfoResponse
	0, // 2: ghost.MatchStatusResponse.match_status:type_name -> ghost.MatchStatus
	1, // 3: ghost.Ghost.GetMatchInfo:input_type -> ghost.MatchInfoRequest
	5, // 4: ghost.Ghost.GetMatchStatus:input_type -> ghost.MatchStatusRequest
	2, // 5: ghost.Ghost.GetMatchInfo:output_type -> ghost.MatchInfoResponse
	6, // 6: ghost.Ghost.GetMatchStatus:output_type -> ghost.MatchStatusResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_ghost_ghost_proto_init() }
func file_ghost_ghost_proto_init() {
	if File_ghost_ghost_proto != nil {
		return
	}
	file_ghost_ghost_proto_msgTypes[1].OneofWrappers = []any{
		(*MatchInfoResponse_Cs2)(nil),
		(*MatchInfoResponse_Dota2)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ghost_ghost_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ghost_ghost_proto_goTypes,
		DependencyIndexes: file_ghost_ghost_proto_depIdxs,
		EnumInfos:         file_ghost_ghost_proto_enumTypes,
		MessageInfos:      file_ghost_ghost_proto_msgTypes,
	}.Build()
	File_ghost_ghost_proto = out.File
	file_ghost_ghost_proto_rawDesc = nil
	file_ghost_ghost_proto_goTypes = nil
	file_ghost_ghost_proto_depIdxs = nil
}
